rate: 1.0
range_min: 0.2
range_max: 2.5
mount_height_min: 0.1
mount_height_max: 0.3
tilt_angle_min: 10.0
tilt_angle_max: 20.0

cam_model_update: false
used_depth_height: 100
depth_img_step_row: 8
depth_img_step_col: 8

ground_max_points: 2500
ransac_max_iter: 2000
ransac_dist_thresh: 0.001

publish_dbg_info: true