output_frame_id: tof_link
rate: 10
range_min: 0.2
range_max: 2.5
sensor_mount_height: 0.2
sensor_tilt_angle: 15.0

publish_depth: true
cam_model_update: false
used_depth_height: 100
block_size: 4
block_points_thresh: 2
depth_img_step_row: 1
depth_img_step_col: 1
ground_margin: 0.1
